---
- name: Deploy and configure Cloud Ops Agent to collect Apache signals
  hosts: localhost
  become: true
  roles:
    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent
        version: latest
        main_config_file: ansible_templates/ops_agent_apache_config.yaml
      notify:
        - Restart Ops Agent

  tasks:
    - name: Install httpd and performance tools
      package: 
        name: 
         - apache2
         - sysbench
         - jq
        state: present

    - name: Template a file, using symbolic modes (equivalent to 0644)
      template:
        src: ansible_templates/httpd.conf
        dest: /etc/apache2/apache2.conf
      notify:
        - Restart httpd

    - name: Start httpd
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start Ops Agent
      service:
        name: google-cloud-ops-agent
        state: started
        enabled: yes
    
    - name: Run a cron job every 5 minutes to generate CPU load using sysbench
      cron:
        name: "5 minute CPU load"
        minute: "*/5"
        job: "sysbench cpu run"

    - name: Generate localhost webtraffic every 3 minutes 
      cron:
        name: "3 minute web traffic load"
        minute: "*/3"
        job: "timeout 120 bash -c -- 'while true; do curl localhost; sleep $((RANDOM % 4)) ; done'"
        
  handlers:
    - name: Restart httpd
      service:
        name: apache2
        state: restarted
        enabled: yes

    - name: Restart Ops Agent
      service:
        name: google-cloud-ops-agent
        state: restarted
        enabled: yes